---
name: PR comment trigger

"on":
  issue_comment:
    types: [created]

jobs:
  check-comment:
    name: PR Comment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    outputs:
      sha: ${{ steps.get-pr-info.outputs.sha }}
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/run-tests' &&
      github.event.comment.author_association == 'MEMBER'
    steps:
      - name: Get PR info
        uses: actions/github-script@v7
        id: get-pr-info
        with:
          debug: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            if (!pr) {
              throw new Error('Pull request not found');
            }
            return {
              sha: pr.head.sha
            };
  build-test-lint:
    name: Build, Test, and Lint
    needs: [check-comment]
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-test-lint.yaml
    with:
      ref: ${{ needs.check-comment.outputs.sha }}
    secrets: inherit
  pr-checkpoint-status:
    name: "PR Checkpoint Status"
    runs-on: ubuntu-latest
    needs: [check-comment, build-test-lint]
    steps:
      - name: Set status check
        uses: actions/github-script@v7
        with:
          debug: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha = '${needs.check-comment.outputs.sha}';
            console.log(context);
